"""Create user model

Revision ID: 9212ef5934d5
Revises: 9646cda6ef73
Create Date: 2022-06-25 01:31:14.496257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9212ef5934d5'
down_revision = '9646cda6ef73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
